"""empty message

Revision ID: 0177ab87c22f
Revises: 5fd60f6014df
Create Date: 2022-01-09 13:10:01.822680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0177ab87c22f'
down_revision = '5fd60f6014df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('node_owner', sa.Integer(), nullable=True))
    op.drop_constraint('content_node_fkey', 'content', type_='foreignkey')
    op.create_foreign_key(None, 'content', 'node', ['node_owner'], ['id'], ondelete='CASCADE')
    op.drop_column('content', 'node')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('node', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.create_foreign_key('content_node_fkey', 'content', 'node', ['node'], ['id'], ondelete='CASCADE')
    op.drop_column('content', 'node_owner')
    # ### end Alembic commands ###
