"""Database level ON DELETE CASCADE keywords

Revision ID: 35eda3577615
Revises: e762637e8e52
Create Date: 2022-01-05 15:51:24.104794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35eda3577615'
down_revision = 'e762637e8e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('keyword_owner_fkey', 'keyword', type_='foreignkey')
    op.create_foreign_key(None, 'keyword', 'content', ['owner'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'keyword', type_='foreignkey')
    op.create_foreign_key('keyword_owner_fkey', 'keyword', 'content', ['owner'], ['id'])
    # ### end Alembic commands ###
