"""empty message

Revision ID: 5fd60f6014df
Revises: a2fb25f80ccc
Create Date: 2022-01-09 12:10:42.945050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd60f6014df'
down_revision = 'a2fb25f80ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('content', sa.Column('node', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'content', 'node', ['node'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_column('content', 'node')
    op.drop_table('node')
    # ### end Alembic commands ###
