"""empty message

Revision ID: 7cd491cb25ee
Revises: 
Create Date: 2022-01-02 15:12:55.162605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cd491cb25ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'content', 'user', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_column('content', 'owner')
    # ### end Alembic commands ###
