"""content user database level ON DELETETE CASCADE

Revision ID: a2fb25f80ccc
Revises: 35eda3577615
Create Date: 2022-01-05 18:55:27.335913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2fb25f80ccc'
down_revision = '35eda3577615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('content_owner_fkey', 'content', type_='foreignkey')
    op.create_foreign_key(None, 'content', 'user', ['owner'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.create_foreign_key('content_owner_fkey', 'content', 'user', ['owner'], ['id'])
    # ### end Alembic commands ###
